# pubspec.yaml

name: permuta_policial
description: Feito por Gabriel Felipe Lopes.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0' # Use a versão do SDK compatível com seu ambiente

# SEÇÃO DE DEPENDÊNCIAS
dependencies:
  flutter:
    sdk: flutter
  
  # Para gerenciamento de estado
  provider: ^6.0.5

  # Para fazer requisições HTTP
  http: ^1.5.0 # Ou a versão  mais recente

  # Para variáveis de ambiente

  # Para armazenamento seguro de dados (token)
  flutter_secure_storage: ^8.0.0

  # Componente de Dropdown com busca
  dropdown_search: ^5.0.6

  # Para abrir links externos (ex: Termos de Uso)
  url_launcher: ^6.1.10

  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.2.1
  cupertino_icons: ^1.0.6
  google_sign_in: ^7.2.0
  flutter_web_plugins: 
    sdk: flutter
  web: ^0.5.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# SEÇÃO DE CONFIGURAÇÕES DO FLUTTER
flutter:
  uses-material-design: true

  # SEÇÃO DE ASSETS (RECURSOS)
  assets:
    # Arquivo de variáveis de ambiente 

    # Pasta de imagens
    - assets/images/